"""add_capital_contributed_to_partners

Revision ID: 0553d75b1b42
Revises: 66191de6ba9e
Create Date: 2026-05-14 11:44:30.514484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0553d75b1b42'
down_revision: Union[str, Sequence[str], None] = '66191de6ba9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_expenses_operation_id'), table_name='operation_expenses')
    op.add_column('operation_partners', sa.Column('capital_contributed', sa.Numeric(precision=12, scale=2), nullable=True))
    op.drop_index(op.f('ix_operation_partners_operation_id'), table_name='operation_partners')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_operation_partners_operation_id'), 'operation_partners', ['operation_id'], unique=False)
    op.drop_column('operation_partners', 'capital_contributed')
    op.create_index(op.f('ix_operation_expenses_operation_id'), 'operation_expenses', ['operation_id'], unique=False)
    # ### end Alembic commands ###
