"""add_tax_regime_to_financials

Revision ID: 2cc8c55aefa1
Revises: eecb2901f4ac
Create Date: 2026-05-13 11:20:56.121999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc8c55aefa1'
down_revision: Union[str, Sequence[str], None] = 'eecb2901f4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_financials', sa.Column('financing_interest_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('operation_financials', sa.Column('financing_loan_months', sa.Integer(), nullable=True))
    op.add_column('operation_financials', sa.Column('buy_commission', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('operation_financials', sa.Column('tax_regime', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation_financials', 'tax_regime')
    op.drop_column('operation_financials', 'buy_commission')
    op.drop_column('operation_financials', 'financing_loan_months')
    op.drop_column('operation_financials', 'financing_interest_rate')
    # ### end Alembic commands ###
