"""add is_active and last_seen_at to listings

Revision ID: 30b2217e8003
Revises: dfb57e6cd86a
Create Date: 2026-05-04 16:28:10.216369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b2217e8003'
down_revision: Union[str, Sequence[str], None] = 'dfb57e6cd86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('listings', sa.Column('last_seen_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'last_seen_at')
    op.drop_column('listings', 'is_active')
    # ### end Alembic commands ###
