"""add notified_at to listings

Revision ID: 35cc1e9bdf31
Revises: 30b2217e8003
Create Date: 2026-05-06 10:34:36.934493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35cc1e9bdf31'
down_revision: Union[str, Sequence[str], None] = '30b2217e8003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('notified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'notified_at')
    # ### end Alembic commands ###
