"""add_operation_partners

Revision ID: 524b41c51f6f
Revises: 2cc8c55aefa1
Create Date: 2026-05-13 11:52:59.196202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524b41c51f6f'
down_revision: Union[str, Sequence[str], None] = '2cc8c55aefa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('participation_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('loan_interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('loan_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_partners')
    # ### end Alembic commands ###
