"""add_score_reasoning_flags

Revision ID: dfb57e6cd86a
Revises: afb84d6a4a3d
Create Date: 2026-04-14 19:04:29.437406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb57e6cd86a'
down_revision: Union[str, Sequence[str], None] = 'afb84d6a4a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('score_reasoning', sa.Text(), nullable=True))
    op.add_column('listings', sa.Column('score_green_flags', sa.Text(), nullable=True))
    op.add_column('listings', sa.Column('score_red_flags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'score_red_flags')
    op.drop_column('listings', 'score_green_flags')
    op.drop_column('listings', 'score_reasoning')
    # ### end Alembic commands ###
