"""add_deal_tracker_tables

Revision ID: eecb2901f4ac
Revises: 35cc1e9bdf31
Create Date: 2026-05-12 21:08:03.701234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eecb2901f4ac'
down_revision: Union[str, Sequence[str], None] = '35cc1e9bdf31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('participation_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=300), nullable=False),
    sa.Column('role', sa.Enum('admin', 'viewer', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('prospecto', 'negociacion', 'compra', 'en_obra', 'en_venta', 'vendido', name='operationstatus'), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_dates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('offer_date', sa.Date(), nullable=True),
    sa.Column('arras_date', sa.Date(), nullable=True),
    sa.Column('escritura_date', sa.Date(), nullable=True),
    sa.Column('renovation_start', sa.Date(), nullable=True),
    sa.Column('renovation_end', sa.Date(), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_table('operation_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('category', sa.Enum('compra', 'reforma', 'reforma_extra', 'suministros', 'comunidad', 'honorarios', 'agencia', 'financiacion', 'impuestos', 'otros', name='expensecategory'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_by', sa.Enum('francisco', 'german', 'sl', 'ambos', name='paidby'), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_financials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_taxes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_notary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('renovation_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('target_sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sale_agency_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sale_tax_estimate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('financing_own_capital', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('financing_borrowed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('financing_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_table('partner_distributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('distributed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frequency', sa.Enum('monthly', 'quarterly', 'annual', name='frequency'), nullable=False),
    sa.Column('category', sa.Enum('compra', 'reforma', 'reforma_extra', 'suministros', 'comunidad', 'honorarios', 'agencia', 'financiacion', 'impuestos', 'otros', name='expensecategory'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('auto_generate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_expenses')
    op.drop_table('partner_distributions')
    op.drop_table('operation_financials')
    op.drop_table('operation_expenses')
    op.drop_table('operation_dates')
    op.drop_table('operations')
    op.drop_table('users')
    op.drop_table('partners')
    # ### end Alembic commands ###
